# Generated by Django 5.1 on 2024-08-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VendorProfile",
        ),
    ]
